# Generated by Django 2.2.4 on 2021-03-19 10:33

from django.db import migrations

def transfer_owners_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
         Owner.objects.get_or_create(
             owner=flat.owner, 
             owners_phonenumber=flat.owners_phonenumber,
             owner_pure_phone=flat.owner_pure_phone)
        

def clean_owners_data(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RunPython(transfer_owners_data, clean_owners_data),
    ]
