# Generated by Django 2.2.4 on 2021-03-22 04:09

from django.db import migrations
import phonenumbers

def connect_flats_data_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.set(Flat.objects.filter(owner_pure_phone=owner.owner_pure_phone))

def clean_flats_data_from_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210319_1333'),
    ]

    operations = [
        migrations.RunPython(connect_flats_data_to_owner, clean_flats_data_from_owner),
    ]
