# Generated by Django 2.2.4 on 2021-03-23 06:22

from django.db import migrations

def clear_data_of_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner = None
        flat.owners_phonenumber = None
        flat.owner_pure_phone = None
        flat.save()




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20210323_0930'),
    ]

    operations = [
        migrations.RunPython(clear_data_of_owners_flats),
    ]